### ISSUE TITLE
Cache type and owner parsing not OK (Website change)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10421]
## Bug description 

Users report problems, that cache type and partly other information is missing after loading cache details.
There was also a website change today, so it might be caused by that:
https://forums.geocaching.com/GC/index.php?/topic/361563-release-notes-website-links-now-point-to-new-search-results-april-20-2021/

### Steps to reproduce the problem

- Open cache details of an unsaved  cache

### Actual result after these steps 

- Cache type is shown as "??" 

### Expected result after these steps 

Cache type parsing working

## c:geo version 

2021.04.15

## Reproducible 

Yes

## System information 

not relevant

## Additional context 

Other problems might apply, e.g. owner has some problem
Taken from a users log:
```
4-20 20:00:10.998  6897  9615 W cgeo    : [Thread-17] owner not parsed correctly for GC97Z19
04-20 20:00:10.999  6897  9615 W cgeo    : [Thread-17] type not parsed correctly for GC97Z19
04-20 20:00:16.265  6897  4136 W DpmTcmClient: read failed bytes countRead: -1
04-20 20:00:17.523  6897  9615 W cgeo    : [Thread-17] owner not parsed correctly for GC97WH4
04-20 20:00:17.523  6897  9615 W cgeo    : [Thread-17] type not parsed correctly for GC97WH4
04-20 20:00:22.620  6897  9615 W cgeo    : [Thread-17] owner not parsed correctly for GC96ZMP
04-20 20:00:22.620  6897  9615 W cgeo    : [Thread-17] type not parsed correctly for GC96ZMP
```

**Comment by Lineflyer** [comment]
A fix for this need to target `release`

**Comment by Lineflyer** [comment]
Example scenario:
- Search for GC97Z19
- Cache type is shown as "??" instead of "Mystery"

The owner however looks normal to me.

**Comment by Lineflyer** [comment]
Raised a user notification

**Comment by moving-bits** [comment]
I'm working on it...

**Comment by moving-bits** [comment]
Fixing the cache type seems to be pretty straightforward, but for the owner the cache details page only contains the guid now, and no longer the user id. I'll push a PR for the cache type, but let's keep this open as we need to find a solution for the user id as well.

**Comment by moving-bits** [comment]
Hm, although it complains in the log about not being able to parse the owner correctly (which is true, at least with regard to the owner's user id), it still displays the owner and seems to offer all owner options. (Maybe the owner guid is enough for that? Although querying the owner user id is done quite frequently in our code.)

**Comment by Lineflyer** [comment]
No, its not:
You cannot search for caches hidden/found by that user. It shows an error toast "No username".

**Comment by moving-bits** [comment]
Hm, I just took the cache I'd used for developing the fix. The cache is now stored in my list. If I do a tap on the cache owner name and select "hidden" I get a list of several cache from the same owner, caches, which are not yet stored on my device.
Maybe that relation gets detected by some other means during storing a cache detail page? Need to investigate...

**Comment by moving-bits** [comment]
At least the tests regarding a cache owner are failing:
-    cgeo.geocaching.CgeoApplicationTest.testSearchByGeocodeBasis
-    cgeo.geocaching.CgeoApplicationTest.testSearchByGeocodeSpecialties

Also a mocked cache file needs to be updated: (will do)
-    cgeo.geocaching.connector.gc.GCParserTest.testParseCacheFromTextWithMockedData

**Comment by Lineflyer** [comment]
If you give up for today, we could also push a release with the cache type fix.
The missing owner info is obviously only causing a problem for a rather special function...so this could IMHO wait some more days in case of need.

I checked plain owner search and all other searches...besides what we already found, the rest looks normal.

**Comment by moving-bits** [comment]
Just discovered (while analyzing the error regarding the mocked cache) that detecting a cache type with the new pattern won't work for archived caches, as the link I'm using for it is not present on cache pages for archived caches. I'll see if I can find a different way for type detection.

**Comment by moving-bits** [comment]
Ok, found a solution for the problem with archived pages (and yet another problem regarding data formats), all of which is fixed in #10423.

The "owner user id" problem is still untouched, though, don't have a quick solution at hand. I guess we will have to find a new page where the owner's user id is being displayed somewhere, and get it from there. 

Needs to be investigated, so I guess we should push a fix for the cache type problem separately and do not wait for the owner thing.

**Comment by bekuno** [comment]
The owner search is ok back right now.
Seems that GC fixed that themself.
Btw, the last hour I could not login (c:geo) or logout (website). Maybe GC worked on their servers.

**Comment by Lineflyer** [comment]
> The owner search is ok back right now.
Seems that GC fixed that themself.

Can't confirm this.
FYI: In c:geo it seems to depend whether you have already stored the relation between username and its GUID (don't know from where). If I open a random GC code and try to view caches hidden by that cache owner I do still see the error toast "No username".

**Comment by bekuno** [comment]
> 
> 
> > The owner search is ok back right now.
> > Seems that GC fixed that themself.
> 
> Can't confirm this.
> FYI: In c:geo it seems to depend whether you have already stored the relation between username and its GUID (don't know from where). If I open a random GC code and try to view caches hidden by that cache owner I do still see the error toast "No username".

@Lineflyer 
My way to the cache was from the map. Move the live map in a area with unsaved caches, then open one of them.
In the preview the content (icon) is ok.
In the detail view the icon is not ok. Please check if the fix works here also.
From this detail view the search by username works.

**Comment by Lineflyer** [comment]
The cache type icon is OK for me in all scenarios using the newest nightly 2021.04.21-NB1 (which I created this morning).

Interesting enough the owner problem is indeed not appearing when going through the live map as @bekuno describes:
- Scroll live map to find an unsaved (never opened) cache
- Open the cache details from there
- Owner related actions after tapping on user name (e.g. "Hidden by this owner") are working

If I however perform a search by coordinates or GC code to open an unsaved (never opened) cache the owner related actions are not working. 
Maybe that helps to find a solution.

**Comment by MagpieFourtyTwo** [comment]
WFM: No matter how I access a (previously not viewed) cache listing (tried via Live Map and by search for City), looking up the listing owner's hidden or found caches does work.

JFTR: With the latest nightly the cache type/icon is working over here, too, again.

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo Can you try to directly open a cache with its geocode (e.g. GC77) and try there: Tap on owner name - Tape "Hidden caches".
It seems the GUID is also prefilled if you come from a list, but not for only loading the cache details directly (which is strange...but I don't know the code difference behind).

**Comment by fm-sys** [comment]
I think I found a solution for parsing the owner name. PR will follow...

**Comment by MagpieFourtyTwo** [comment]
> Can you try to directly open a cache with its geocode (e.g. GC77) and try there: Tap on owner name - Tape "Hidden caches".
> It seems the GUID is also prefilled if you come from a list, but not for only loading the cache details directly (which is strange...but I don't know the code difference behind).

Assuming that #10434 does not distort the result, I can reproduce this scenario; If I open GC77 directly via GC code input into the magnifier search field, it shows ``Ferenc (adopted by BlackyV)`` as owner, but although clicking on it even opens the popup, clicking ``Caches hidden`` results in a ``No Username given`` toast. Same with ``Caches found``. Just ``Open profile in browser`` and ``Send message`` do work, while ``Send email`` ends up in the incomplete  link ``geocaching.com/email/?u=``.

**Comment by moving-bits** [comment]
That's probably because some user-related functions on gc.com require a user-id, while others require a guid. The guid we are still able to retrieve, whereas for the user-id we need to adapt to yesterday's website change. (Haven't had a chance to look into #10430 yet - maybe we have a fix for that as well, meanwhile.)

**Comment by Lineflyer** [comment]
@moving-bits 
@fm-sys 

As the functional bug is solved thanks to your PRs I will close this issue. Please feel free to open follow-up issues, e.g. regarding:

- Fix login names with special chars
- Maybe use  https://www.geocaching.com/play/serverparameters/params as suggested by @bekuno in https://github.com/cgeo/cgeo/pull/10436#issuecomment-824372637

**Comment by Lineflyer** [comment]
Latest status of `release` stil has the owner problem for unsaved/unknown owners in some context.
Will open up a new issue, but I dont consider it blocking for releasing a new version by now.

**Comment by MagpieFourtyTwo** [comment]
Should be reopened, cause Owner extraction still does not work in some cases.

Most regretfully was not able to nail a scenario: sometimes it works, sometimes it doesn't, even with the same owner name. With e. g. https://coord.info/GC99HF8 I would say, understandable, because of the ampercent, but in https://coord.info/GC96WYF I don't get the owner neither, although has name has no special chars at all, and although in https://coord.info/GC96WWV it works perfectly fine.

**Comment by MagpieFourtyTwo** [comment]
Oops, just saw last comment of @Lineflyer - will keep an eye on the new issue. ;)
