### ISSUE TITLE
Caches deleted in the map view do not disappear from the map

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#10428]
## Bug description 

When you delete a cache using the map view, the cache does not disappear. You always have to go back to the list view, and then to the map view again, to make it disappear. Doing that resets the map zoom, so it is incredibly annoying. This bug should be fixed. Thank you very much!

**Comment by dcjkfgdjhd** [comment]
Any news on this very annoying issue? Thanks.

**Comment by Lineflyer** [comment]
Can you please provide more details?

- From where did you start the map (e.g. map of a list of stored caches)?
- What map source (Google or OSM)?
- Was the map in live mode?

**Comment by dcjkfgdjhd** [comment]
Yes, a map launched from a list of stored caches, *not* in live view mode. So I only see stored caches. When I tap on a cache on the map and delete it, it is still displayed on the map, just without the "disk" icon (that was indicating that it was stored).

Use case: I usually pre-plan what caches I want to do on a tour, and store them on the device, and do not use liveview. This way, unplanned caches do not distract me from my plan. Once I found a cache, I delete it, so that it does not distract me any longer. But the icon does not disappear, unless I go back to the stored list, and reopen the map, so that it gets drawn fresh.

**Comment by Narrat** [comment]
Can confirm this behaviour. Although it doesn't annoy me that much.

**Comment by dcjkfgdjhd** [comment]
What makes it so irritating for me is that when you go back to the list view and then reopen the map, the map zoom is reset everytime and you have to zoom back in to where the map was before.

**Comment by dcjkfgdjhd** [comment]
This problem still exists. For me personally, it is by far the most annoying bug in c:geo.

In the current version, it also appears in the "opposite direction": When in map view for a stored list, and you create a new custom cache while using the "use current list" option is enabled, that new cache DOES get created in the current list, but NOT drawn immediately. You have to go back to list view, and then back to list map view, to get it to draw.

**Comment by edgarbriggs** [comment]
I can inform all three mentioned points and suggest they should be fixed:

- deleted cache doesn't disappear from map 
- new custom cache doesn't appear on map
- going back from map to list, and then back to map, resets the map zoom

The last point is the most important. I agree with the thread starter that this is by far the most annoying "feature" of c:geo.

**Comment by dcjkfgdjhd** [comment]
Sorry to bump this, but:

Any chance we will see a fix for this issue soon? For me personally it is by far the most annoying bug in c:geo. It bothers me *every single time* I use c:geo.

**Comment by moving-bits** [comment]
> When you delete a cache using the map view, the cache does not disappear.

If I'm not mistaken this part is done intentionally to prevent caches being deleted by accident. If you hit "delete" on the wrong cache, you can easily restore it by pressing "save".

> You always have to go back to the list view, and then to the map view again, to make it disappear. Doing that resets the map zoom

"Resetting" zoom level is also done intentionally: If you are displaying the contents of a list, the zoom adjusts to a level that all caches in this list are visible, which is what you would want in most cases.

But I do understand that the combination of both may hit you in your use-case.

So if directly removing a cache from the map without leaving the map is not possible, a different approach for you could be to set some visual marker to those caches you want to ignore. For example: Instead of deleting a cache in map view, you could move those caches to a different list specifically used for this reason, and set a list marker for that list (eg: a red dot) - than you can easily spot which caches should be ignored.

**Comment by dcjkfgdjhd** [comment]
> If I'm not mistaken this part is done intentionally to prevent caches being deleted by accident. If you hit "delete" on the wrong cache, you can easily restore it by pressing "save".

If that is the reason for this behaviour, then IMHO it should be solved differently. For example, a deleted cache could become half-transparent, and over 15 (?) seconds it could slowly fade and become more and more transparent, until it disappears completely, giving the user enough time to re-save it if needed.

Alternatively, there could be an "Undo" bar displayed after deletion, as most Android apps do it (e.g. Gmail).

> "Resetting" zoom level is also done intentionally: If you are displaying the contents of a list, the zoom adjusts to a level that all caches in this list are visible, which is what you would want in most cases.

I don't agree that is the behaviour that is wanted "in most cases". This behaviour only makes sense when you prepare a cache list in advance. E.g. I am sitting in Berlin and I am preparing a cache list with caches in Paris for my trip to Paris next week. Then this "show all" behaviour makes sense.

But if I am already *there* (e.g. my location is somewhere within the bounding box of all caches in the list), it is much more likely that I am currently walking around caching, and therefore I am probably much more interested in the caches close to me, thus resetting zoom / zooming out makes no sense.

> So if directly removing a cache from the map without leaving the map is not possible, a different approach for you could be to set some visual marker to those caches you want to ignore. For example: Instead of deleting a cache in map view, you could move those caches to a different list specifically used for this reason, and set a list marker for that list (eg: a red dot) - than you can easily spot which caches should be ignored.

There are many workarounds imaginable but they don't truly achieve the goal of decluttering the map view.

**Comment by edgarbriggs** [comment]
> "Resetting" zoom level is also done intentionally: If you are displaying the contents of a list, the zoom adjusts to a level that all caches in this list are visible, which is what you would want in most cases.

I also have to disagree. For me, resetting zoom level is *never* the desired behaviour, and I would be very happy if there was an option to keep the zoom level. My personal "most wanted" wish for c:geo. ;-)

**Comment by Lineflyer** [comment]
@moving-bits 

> If I'm not mistaken this part is done intentionally to prevent caches being deleted by accident. If you hit "delete" on the wrong cache, you can easily restore it by pressing "save".

The initial user refers to mapping a list and deleting a cache on the map, but not about the general live map view.
On the live map view it is as you described for a good reason, but if you remove a member of a mapped list it could be gone from that map view immediately. AFAIR we also have a similar issue, where a user moved a cache on a mapped list to another list and it also did not disappear.

I will change the subject here accordingly.

**Comment by moving-bits** [comment]
To my understanding we are talking about different things here:
- Deleting a cache: triggers our "grace period", so cache stays on map. I don't understand why there should be a difference here between handling of deleting a cache from live map or from cache list map.
- Removing a cache: We don't have an actual "remove from map" function yet, only thing available is "move cache out of currently displayed list". To make this remove the cache from cache list map would require a couple of changes, though, as we are actually not displaying "all caches from list x", but just a set of caches, which just happened to be in the same list when we started the map display. After starting the map we don't have the info that we are displaying the contents of a certain list anymore. (The title displayed in the header is just a string without a technical relationship to the opening list.) Thus we have no way to detect that removing a specific list assignment from a cache should trigger it's removal from the map.

A solution to this could be to add an entry to the cache's context menu: "remove from map", which would remove this cache from the set of displayed caches without changing anything else.

**Comment by fm-sys** [comment]
> A solution to this could be to add an entry to the cache's context menu: "remove from map", which would remove this cache from the set of displayed caches without changing anything else. 

What would be the benefit of such a feature? I would strongly suggest to design UI in a way that actually make sense, and not just add menu entries for everything which can be done without much implementation effort.

E.g. we could implemented "show list on map" in a context aware way (for unified map). We had the same discussion with regard to filters but postponed it at that time.

**Comment by moving-bits** [comment]
> we could implemented "show list on map" in a context aware way (for unified map).

Agreed, this is also the way we had discussed for Unified Map (https://github.com/cgeo/cgeo/discussions/13121#discussioncomment-2926070), and the foundation is laid for this with `UnifiedMapTypeType`.

Above's proposal was just mentioned as a possible workaround for today's maps for the TO's issue, which seems to be pretty annoying for their day to day use-cases.

**Comment by dcjkfgdjhd** [comment]
> I also have to disagree. For me, resetting zoom level is _never_ the desired behaviour, and I would be very happy if there was an option to keep the zoom level. My personal "most wanted" wish for c:geo. ;-)

I just came back from a 700km bike tour which I had planned ahead of time. 

The "zoom reset" behaviour is absolutely maddening in such a situation. Everytime I have to re-open the map view of the list (and I need to do this often, for the reasons discussed above, every time I move a found cache from the standard list to my "found caches" list), c:geo zooms out very, very far to display all 700km...

**Comment by moving-bits** [comment]
How about the following workaround:
- map a list, zoom to the scale you want it to have, work with the map etc.
- delete a cache if required => go back to list => tap on "map" icon in bottom navigation (instead of "mapping the list")

This should open map view in the last zoom state, displaying all caches in that area.
So you may see more caches (not only those contained in the list), but zoom does not get reset.

**Comment by dcjkfgdjhd** [comment]
> you may see more caches (not only those contained in the list)

I am not sure I understand. That defeats the purpose of lists in general *and* the purpose of deleting a cache from a list in the first place, doesn't it?

**Comment by bekuno** [comment]
Maybe fixed by https://github.com/cgeo/cgeo/pull/16660.
Please retest it.

**Comment by moving-bits** [comment]
And for the zoom issue, #16558 might help. Please retest and let us know if anything from this issue remains open. Thanks.

**Comment by dcjkfgdjhd** [comment]
Yes, the non-disappearing issues seems solved. Thank you very much! 

The zoom problem is only partially solved, will comment on the other issue.
