### ISSUE TITLE
Unneeded file copy dialog on clean install

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11846]
### Describe your problem!

While playing testing the c:geo installation on various "out-of-the-box" (wiped) emulators I noticed a wrong behavior.
After selecting a base folder the dialog for copy/move from previous base folder is shown while there is no previous base folder in that case.

### How to reproduce?

- Wipe API30 emulator
- Build and install c:geo on it
- Run the wizard
- Provide permissions as requested
- When selecting the base folder, create a new folder (my example: cgeo123) and select it as base folder
- Confirm allowing c:geo to access this folder

### Actual result after these steps?

The "change folder base" dialog is shown:

![image](https://user-images.githubusercontent.com/949669/136784274-6db62437-b7e3-44cf-8f8e-5839e0e606a5.png)

### Expected result after these steps?

This dialog should be skipped as there is no change but the base folder was assigned for the first time.

### Reproducible

Yes

### c:geo Version

Current master 11.10.2021

### System information

```text
Android 11 (API30) emulator
Pixel 4
```

**Comment by eddiemuc** [comment]
Fixed with PR #12294

**Comment by fm-sys** [comment]
Once again tried our onbording experience. Actually still reproducible...

![Screenshot_20230107_092436_cgeo geocaching](https://user-images.githubusercontent.com/64581222/211141376-10e38081-0f9d-4714-9d29-d2f2c031625a.jpg)
