### ISSUE TITLE
Align attribute categories with GC?

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12421]
While working on #12310 I just noticed that GC also has categories for icons, altough only hidden on some help page: https://www.geocaching.com/about/icons.aspx

Maybe we should align our categories with them? But in some cases I disagree, e.g.
- Night cache -> should be equipment (our tools)
- May require swimming -> should be equipment (our tools)

 @moving-bits you implemented the current categories, any opinion?

**Comment by ztNFny** [comment]
addressed in #12424

**Comment by moving-bits** [comment]
> @moving-bits you implemented the current categories, any opinion?

I'd just copied them from your proposal :-)

But anyway, no strong opinion about this. I guess, nearly nobody knows the categories used by gc.com, as they rarely used in their systems, so no need to follow them, IMHO.

**Comment by Lineflyer** [comment]
My preference follows GC.com:
- Night cache is more condition than tool (there might be night caches which don`t require tools but just your eyes, e.g. the laser cache in Hannover (if still existing)). Flashlight, UV, etc. can be set on top as tools.
- Swimming is just a condition, which does not necessarily require tools (in contrast to wading). Boat required is a dedicated tool attribute.
