### ISSUE TITLE
Offline map opens slower if activity history is long

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12813]
### Describe your problem!

Today I had a day off and went caching spontaneously driving from cache to cache.
After a while I noticed, that when "mapping a cache" it took some seconds for the map to show up. It got worse and worse over the day.

Back home I tried again and realized, that I could use the back key of my device quite a lot of time iterating over several map activites until finally reaching the state "press again to exit".

Once I did this opening the cache map was fast again.

### How to reproduce?

 I tried again to open list, home, map, cache, back to list, and so on and could (kind of) reproduce, that opening the map for a cache or even the "normal" map got slower to start again.

### Actual result after these steps?

If you have such long activity history, open the details of a cache and then long-click the compass rose to open the map for the cache.
The activity itself opens fast but it takes 2-3 seconds until map and objects are loaded.

### Expected result after these steps?

There is no crash involved, everything worked fine throughout the day (else the activity stack would have been shorter ;) ), but I guess we should limit the activity history somehow and/or find out if several open maps block/slow down something and whether this is avoidable.

Additionally:
IMHO it makes no sense to keep a real long activity history. Do we have set a limit for that?

### Reproducible

Yes

### c:geo Version

2022.02.26-NB

### System information

```text
Android 12, Samsung S20
```

**Comment by moving-bits** [comment]
Shall we limit the activity stack to, let's say, 10 or 15 entries?
I guess no one will like to tap back even further (or just remember what one has done 15 activities earlier :-))

**Comment by Lineflyer** [comment]
AFAIR we discussed this some weeks ago and I thought we already have such limit. If we do not have, it makes IMHO sense to limit to a rather low number like 10 at max.

**Comment by fm-sys** [comment]
Yes, I remember that we had discussed this but until now no one has implemented it... 

10 activities sounds like a good starting point, maybe even 5 would be enough? OTOH, who knows how our users are using the app. With 10 activities we should be on the safe side (hopefully).

Side note: I have absolutely no idea how such a limit could be implemented cleanly. But maybe someone else has a good idea :)

**Comment by moving-bits** [comment]
I've found no way yet to count every activity opened within the app, but I can count activities opened using the bottom navigation icons, so I implemented a slightly different approach:
- count number of activities opened using the bottom navigation icons; also remember the highest count reached
- on pressing the back key for such an activity, check whether counter's current value is farther than MAX_DEPTH from maximum so far
- if so: show a short toast that pressing back again will close the app (gets reset after two secs) / close on pressing back again within time limit
- (last line's behavior is similar to what we have today when reaching the opening home screen through pressing back button again and again)

See PR #12869 for a proposal. Please review...

**Comment by fm-sys** [comment]
The original request was not "I don't want to press back that often" but rather "cgeo gets slower if activity history is long". So I fear PR #12869 doesn't solve anything and might introduce additional confusion. 

Basically, it's a "not enough RAM" issue. If we find no solution to dynamically close old activities to free up memory, it IMHO makes no sense to limit the activity stack at all.

**Comment by moving-bits** [comment]
> The original request was not "I don't want to press back that often" but rather "cgeo gets slower if activity history is long".

Ok, maybe I got distracted by my own wish of not having to press back button so many times to "close" c:geo, thinking it was somehow related.

> Basically, it's a "not enough RAM" issue.

Not sure if that's the real cause, as Android removes old activities automatically when running low on RAM.

I guess someone needs to debug more deeply into the offending code passage, maybe even do some profiling here to find out what's going on.

**Comment by fm-sys** [comment]
> Ok, maybe I got distracted by my own wish of not having to press back button so many times to "close" c:geo

There's an easy solution: Just use the "home" button instead of "back" ;-)

If we however decide to implement any limit, back should IMHO always navigate to the dashboard before "press back again to exit" can appear. That's how it is implemented currently (even if you open cgeo via a shortcut widget BTW). I often find myself using the back button to navigate back to the dashboard.

**Comment by ztNFny** [comment]
> There's an easy solution: Just use the "home" button instead of "back" ;-)

Home != Back though. When starting c:geo from another app, e.g. a messenger, it's added to that apps stack. Pressing back from c:geo then returns to the app instead of home screen - and you might have something in that app you want to return to you can't otherwise.

**Comment by Lineflyer** [comment]
Not sure how other apps handle this...but definitely we are not handling it in a good way.
After a whole day of Geocaching last weekend I was able to use the back button approx. 20 times before having the toast "Tap again to close c:geo".

Of course I want to have the stack of the last activities to be able to navigate back where I came from. But there needs to some kind of limit.  

How about discarding the activity stack once the user explicitly selects "Home"? Not sure though, how that feels during usage.

Does this page offer any clue about best practices, which helps with our "problem"?
https://developer.android.com/guide/components/activities/tasks-and-back-stack

**Comment by fm-sys** [comment]
We however have to find a solution to actually close old activities instead of just hiding them (like in https://github.com/cgeo/cgeo/pull/12869). I can have a closer look in a few weeks...

**Comment by nmrsmn** [comment]
I'm not aware of any, surely valid, reasons, but why do we need to keep track of all activities instead of clearing the stack when navigating using the bottom navigation?

**Comment by moving-bits** [comment]
> I'm not aware of any, surely valid, reasons, but why do we need to keep track of all activities instead of clearing the stack when navigating using the bottom navigation?

We want to be able to go back to the previous activity, e. g. when mapping a list of caches (coming from and returning to cache list view), even along a few more steps. Problem is currently, that the activity stack seems to keep track of all called activities since the most recent start of c:geo (where maybe the last five or ten activities would suffice), and that this memorization seems to make c:geo quite laggy after a while. (This issue may be related to #12498 and #12873.)

**Comment by nmrsmn** [comment]
And to go through that list of caches the user needs to navigate using the bottom navigation right? I get the point of being able to back to the previous activity when mapping a list of caches, but what we maybe could do is determine how users actually are navigating through the app. If for example the user isn't using the bottom navigation (but once, at the start) for coming from and returning to cache list view when mapping a list of caches you could reset the stack upon navigating using the bottom navigation, which should close previous activities and makes c:geo less laggy in the least. But if you need to use the bottom navigation to navigate between caches (which I'm not sure of, because I don't use the back button that much) this isn't possible.

**Comment by Lineflyer** [comment]
Maybe it would indeed be worth a try to reset the activity stack once the user actively uses the bottom navigation. Use cases like mapping a list and returning to the list would then still work. We could test the usability in our nightlies.
Not sure if there are other relevant use cases across different bottom nav activities, but I guess the bottom nav itself would be the "replacement" of the back action in such cases anyway.

So the functionality would be:
- The activity history starts once the user taps on a bottom navigation element and builds up from there (e.g. Lists - Map of list or Search - result list - map of list) with the ability to use the back key to navigate back through those
- Once the user uses the bottom nav to start another "main" activity the above mentioned history shall be removed and starts with the new activity as basis

Not sure though if the last activity in stack could/should always be the dashboard, e.g. the following example:
- User is on lists
- User selects "Map" from bottom nav
- User presses back key

What shall happen then:
1. Toast is shown "Press again to exit c:geo" and another time back key will leave the app directly from map
2.  As the activity history is empty the user will fall back to the dashboard (signalling, that he reached the end of the history) and he would need another two times back to exit the app

**Comment by fm-sys** [comment]
IMHO the second (or my third variant) is the way to go, as there was quite some feedback at the beginning that the bottom navigation together with direct exit was not intuitive enough. But let's try our voting system once again:

> What shall happen then:
> 
> 1. Toast is shown "Press again to exit c:geo" and another time back key will leave the app directly from map

-> Vote with "party" (🎉) 

> 
> 2. As the activity history is empty the user will fall back to the dashboard (signalling, that he reached the end of the history) and he would need another two times back to exit the app

-> Vote with "rocket" (🚀)

> Or my personal idea / my favorite:
>
> 3. As the activity history is empty the user will fall back to the dashboard. However, no "Press again to exit" is shown so another time back key will exit c:geo directly. (Similar to pre-bottomnav behavior) 

-> Vote with "heart" (❤️)

**Comment by Lineflyer** [comment]
Voted "Rocket" as I am one of the hectic users on my back key and therefore thankful for the "Press again to exit", but could get used to live without it. ;)

**Comment by Lineflyer** [comment]
Seems we go for "heart".
As @fm-sys seems to plan working on implementing it, the question would be: `release` or `master`?

**Comment by fm-sys** [comment]
I would target it to `master` so we can test it in the nightlys.

As far as I can see, we have no other critical PRs merged to master, so we could forward the `release` branch to the HEAD of `master` at any time if the PR has proven to work. Correct?

**Comment by Lineflyer** [comment]
Thats correct, but new features will come in.

Principally we should target the branch where we believe the change is suited best.
So if you mean, it could be in the next release if no problem comes up, then lets base it to `release` and merge upstream (as normal) to test in nightlies.
If it turns out counterproductive or buggy we can revert on `release` and merge the revert upstream as well.

**Comment by fm-sys** [comment]
OK, #13000 should solve this issue (targeted to `release`)
