### ISSUE TITLE
[Unified Map] "Long-Click-Filter" not applied

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15470]
### Describe your problem!

Saved filters will not be applied to UM, if activated via LongClick on Filter icon.

### How to reproduce?

1. activate ``Map Sources`` => ``[X] Use Unified Map``
2. open Map
3. long click on Filter icon => ``Clear``
4. all caches will be shown (as expected)
5. long click on Filter icon => select any saved filter (which should make a difference WRT number of visible caches)

### Actual result after these steps?

No change WRT the number of caches shown, filter has not been applied.

### Expected result after these steps?

Filter should immediately be applied.

### Reproducible

Yes

### c:geo Version

2024.03.16-NB-4f30164

### Additional Information

If afterwards you open the filter definition and just click [Ok], the filter will eventually be applied.

**Comment by MagpieFourtyTwo** [comment]
Just remembered another poss. "refresh problem" with Unified Map today:
- had an active route to a cache
- then changed the routing target to it's parking lot (by clicking the [P] icon and then the routing icon in the popup header)
- but ... route did not change at all (although I tried several times)

Maybe over there a refresh is missing, too?

**Comment by moving-bits** [comment]
> Just remembered another poss. "refresh problem" with Unified Map today:

Thanks for reporting. But let's keep those two separate for now, only analysis will show if they have the same cause, and until then two separate items are easier to manage. I'll create a new issue for this.

**Comment by ztNFny** [comment]
I'm unable to reproduce this issue on master. But master was rebased onto release only yesterday at 22:26, so it might be that #15444 wasn't in that build yet. Can you test tomorrow?

**Comment by MagpieFourtyTwo** [comment]
Just observed that it may depend on the filter: resp. on the change of results:
Seems as if it *fails,* if the second filter should result in *less* caches. But *works,* if the second filter results in *more* caches.
In fact, I just did the following:
1. made a very restrictive filter which ended up with just one cache on display
2. switch to a saved filter, which results in 19 caches

This way, the effect of the second filter showed up immediately.
But then switching to another saved filter, which would result in no caches at all had no effect at all.

**Comment by ztNFny** [comment]
Still unable to reproduce with this additional info.

**Comment by MagpieFourtyTwo** [comment]
https://github.com/cgeo/cgeo/assets/9889015/a6cd6ba8-3b88-46f2-962e-bc175b4d2cec

Definition of my "Live" filter:
- Status
  - Show Active;Yes - Disabled:Yes - Archived:No
  - Found: No
  - Has Offline Found Log: No
  - Owned: No

**Comment by ztNFny** [comment]
Live map is the key. Offline lists work perfectly fine, on Live no filter is applied for me at all.
@moving-bits any idea?

**Comment by MagpieFourtyTwo** [comment]
A picture is worth a thousand words.  ;)

**Comment by murggel** [comment]
Hopefully fixed with PR #15576

**Comment by MagpieFourtyTwo** [comment]
Not really. Filter is still not applied after changing to a "more restrictive" filter via long click on the filter icon.
Filter is only applied after visiting filter definition screen (w/o any changes) or leaving and re-entering map.
Tested version is today's nightly (2024.04.13-NB-4ae1565).

**Comment by murggel** [comment]
The mentioned PR is not yet included in the current nightly

**Comment by MagpieFourtyTwo** [comment]
Ok, then I'm happy to get in touch within the next days. ;)

Nevertheless, I'm currently experiencing another problem, this time with individual routes. Have a round trip through a wood with the parking lot at the end. Set route to target is activated. As soon as a cache has been logged, it will be removed from the route and the target is automatically set to the next one, as expected. But as soon as I move, or c:geo thinks it should re-route, the n the route is always drawn as a complete circle. Disabling visibility and enabling it again fixes the problem, the route will then be displayed correct again. At least until logging the next cache and moving on - then the route is a complete circle again.

**Comment by MagpieFourtyTwo** [comment]
Oh, just realized that I'm in the wrong thread - will move it to the correct one this evening.

**Comment by MagpieFourtyTwo** [comment]
Oh, just realized that I'm in the wrong thread - will move it to the correct one this evening.
