### ISSUE TITLE
missing spoiler pics in GC601B

### ISSUE THREAD

**Issue by tinkus-gc** [cgeo/cgeo#15993]
### Describe your problem!

The cache GC601B has two spoiler pictures which can be found in the listing. You can see them in the browser but not in c:geo, see attached screenshots.

### How to reproduce?

Open the cache listing in the browser and in c:geo.

### Actual result after these steps?

Pictures not shown in c:geo

### Expected result after these steps?

Pictures should be visible in c:geo

### Reproducible

Yes

### c:geo Version

2024.08.09-RC

### System information

```text
## System information

c:geo version: 2024.08.09-RC

Device:
-------
- Device type: Pixel Tablet (tangorpro, google)
- Available processors: 8
- Android version: 14
- Android build: AP2A.240805.005
- Screen resolution: 1600x2448px (800x1188dp)
- Pixel density: 2.0
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 24.31.37 (190400-662270918)
- Memory:  Available:1,7 GB, Total:7,3 GB, Threshold: 216,0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:323
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: 23. Juli, 20:01
- Last auto backup: never
- Routing mode: Straight (shortest.brf / trekking.brf / car-eco.brf / car-fast.brf / fastbike.brf)
- Live map mode: false
- Use unified map: true
- OSM multi-threading: true / threads: 4
- Map: Germany (OAM) (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:mapfiles/Germany (OAM).map
  - Atts: #VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2024 #Hoehendaten: sonny.4lima.de, viewfinderpanoamas.org, NASA #Kartendaten: openstreetmap.org
  - Theme: Elevate.zip:Elevate.xml

Filters:
-------
- Hide waypoints: original visited
- LIVE: Status: Archivierte ausschließen ({"advanced":true,"inconclusive":false,"tree":{"type":"status","config":{"values":["exclude_archived"]}}})
- OFFLINE: Keine ({"advanced":true,"inconclusive":false})
- Additional stored filters: 8

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   - Geocaching.com Adventure Lab
   - opencaching.de: Logged in (Anmeldung OK)
- Geocaching.com date format: dd/MMM/yyyy
- Geocaching.com website language: de-DE
- Last login error on geocaching.com: communication error //  (2024-07-23 20-49)
- Last successful login on geocaching.com: 2024-08-21 09-32
- Routing: internal / BRouter installed: false

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (102,9 GB free) v3 internal isDir(10 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (102,9 GB free) v3 internal isDir(10 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (102,9 GB free) v3 external non-removable isDir(7545 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (102,9 GB free) v3 internal isDir(5 entries)
- Map render theme path: Elevate.zip:Elevate.xml
- Public Folders: #13
  - BASE: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo (av:true, files:>=1, size:>=135,6 KB, free:>=102,9 GB)
  - OFFLINE_MAPS: content://com.android.externalstorage.documents/tree/primary:mapfiles/document/primary:mapfiles (av:true, files:>=23, size:>=22,4 GB, free:>=102,9 GB)
  - OFFLINE_MAP_THEMES: content://com.android.externalstorage.documents/tree/primary:mapstyles/document/primary:mapstyles (av:true, files:>=4, size:>=999,3 KB, free:>=102,9 GB)
  - OFFLINE_MAP_SHADING: content://com.android.externalstorage.documents/tree/primary:mapfiles/document/primary:mapfiles/_hgt (av:true, files:>=0, size:>=0 B, free:>=102,9 GB)
  - LOGFILES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/logfiles (av:true, files:>=1, size:>=135,6 KB, free:>=102,9 GB)
  - GPX: content://com.android.externalstorage.documents/tree/primary:Download/Geocaching/document/primary:Download/Geocaching (av:true, files:>=73, size:>=51,4 MB, free:>=102,9 GB)
  - BACKUP: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/backup (av:true, files:>=16, size:>=834,7 MB, free:>=102,9 GB)
  - FIELD_NOTES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/field-notes (av:true, files:>=0, size:>=0 B, free:>=102,9 GB)
  - SPOILER_IMAGES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/GeocachePhotos (av:true, files:>=0, size:>=0 B, free:>=102,9 GB)
  - ROUTING_BASE: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/routing (av:true, files:>=17, size:>=1,1 GB, free:>=102,9 GB)
  - ROUTING_TILES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/routing/segments4 (av:true, files:>=9, size:>=1,1 GB, free:>=102,9 GB)
  - WHERIGO: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/wherigo (av:true, files:>=0, size:>=0 B, free:>=102,9 GB)
  - TEST_FOLDER: file:///data/user/0/cgeo.geocaching/files/unittest (av:true, files:>=0, size:>=0 B, free:>=102,9 GB)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #4
  - content://com.android.externalstorage.documents/tree/primary:mapstyles (8. Jan., 15:03):RW
  - content://com.android.externalstorage.documents/tree/primary:Download/Geocaching (8. Jan., 15:03):RW
  - content://com.android.externalstorage.documents/tree/primary:cgeo (8. Jan., 15:00):RW
  - content://com.android.externalstorage.documents/tree/primary:mapfiles (8. Jan., 15:03):RW

Database
-------
- File: /data/user/0/cgeo.geocaching/databases/data (v103, Size:484,0 MB) on system internal storage
- Data: {cg_attributes=134806, cg_caches=20259, cg_caches_lists=22883, cg_categories=427, cg_extension=201, cg_filters=8, cg_lists=89, cg_logCount=88100, cg_logImages=120055, cg_logs=670606, cg_logs_offline=0, cg_logs_offline_images=0, cg_logs_offline_trackables=0, cg_route=0, cg_search_destination_history=0, cg_spoilers=18879, cg_trackables=2529, cg_trail_history=100, cg_variables=13977, cg_waypoints=29607}
- Extension Data: {DBEXTENSION_DOWNGRADEABLE_DBVERSION=1, DBEXTENSION_EMOJILRU=4, DBEXTENSION_FOUNDNUM=5, DBEXTENSION_LAST_TRACKABLE_ACTION=85, DBEXTENSION_ONE_TIME_DIALOGS=7, DBEXTENSION_POCKETQUERY_HISTORY=90, DBEXTENSION_TRACKFILES=9}

--- End of system information ---
```

### Additional Information

![Screenshot_20240821-124523](https://github.com/user-attachments/assets/5fd95fbc-6d76-4582-babb-476c1e384180)
![Screenshot_20240821-124205](https://github.com/user-attachments/assets/0f2f09ed-7075-4e73-8ff4-351fcd69e309)

**Comment by SammysHP** [comment]
This is already fixed and will be included in the next release.

See #15959 for more details.

**Comment by tinkus-gc** [comment]
I'm using c:geo version 2024.09.01 and the bug is still not fixed for GC601B even the release note stating "Fix: Spoiler images no longer being loaded (website change)".

**Comment by bekuno** [comment]
Confirmed.
This looks like a slightly different problem.

There is a `gccounter` link included, which does not work.
Maybe the parser does not work correctly after this bad link.

**Comment by ztNFny** [comment]
> Confirmed.
> This looks like a slightly different problem.
> 
> There is a `gccounter` link included, which does not work.
> Maybe the parser does not work correctly after this bad link.
> 

gccounter images are ignored by c:geo (there's a blacklist in code)
