### ISSUE TITLE
Event cache shown with wrong date if GMT offset is negative

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4671]
From support mail:

The cache OU079E is shown to be held on `Friday, May 1, 2015` instead of May2nd, 2015 like shown on website.

According to the info from @samueltardieu we save it as `May 2nd, 0:00GMT` which makes it show up incorrect for all people with negative GMT offset.
I am not sure which connectors are affected by that (never got any reports for GC so far).

**Comment by hichris1234** [comment]
The data from opencaching says the event is to be held at `2015-05-02T00:00:00+00:00`. We take this to be GMT, and convert it to the specific timezone.

I'm not sure of a good solution for this. It seems like opencaching is actually at fault here, as their data claims this event will be taking place at midnight GMT, wheras it should at least be midnight EDT, if not 9:00 EDT.

**Comment by Bananeweizen** [comment]
Hm. A rather easy fix would be to parse the string as local time zone always. Right now we enforce parsing as zulu time zone in the date format pattern. That would basically make everyone get event dates as midnight local time when storing a cache. Works fine, just tested.

However, with that I see more trouble: Imagine a user that has daylight saving times in his timezone. He/she goes into/out of daylight saving times after that cache has been saved (with the above mentioned parse change). Then the system will of course display the adapted time afterwards, i.e. 1 hour more or 1 hour less. That means at some point of the year suddenly for all users in a timezone with daylight saving times all event caches will go to the day before the event (as they are now calculated as 23:00 o clock of the day before the event). I believe this issue might actually be worse then the initial problem.

**Comment by Lineflyer** [comment]
Any idea for a workaround or fix which could be included in the upcoming release?

**Comment by samueltardieu** [comment]
I don't think we should rush something in.

**Comment by Bananeweizen** [comment]
Basically this can only be fixed by storing the date as a date only, not as a Unix timestamp. So it needs a database change and maybe has some other side effects.

**Comment by Lineflyer** [comment]
Coming back to this one:
A user from GMT-5 contacted us, that events are "sometimes" shown with wrong date in c:geo.

I assume, that this is still happening due to the above described time zone difference (as we do assume the event date to be GMT). Such bug can be pretty annoying if you live in a GMT-5 timezone and events start being shown as "Today" (on 7pm the evening before in case of this user).

Timezone things are always a bit tricky, additionally we do meanwhile have the possibility to record the specific event time (see #7243) and we could also improve adding the event to a calendar (see #6291 as reference).

If someone wants to dive into it, feel free. 

Assuming that event caches do still not provide any time zone information(?), the only solution seems to be to not use any timezone when storing the event data (as suggested above).

**Comment by Lineflyer** [comment]
It seems we recently gain quite some new users in Australia / New Zealand as there are two new reports on support mail dealing with this issue.

In this case the user is located in "GMT+12" and the matching time zone is set in their devices according to our system information.

One user had a more precise info which might be helpful to identify and fix one case:
- The event cache is stored on his device (Event date: 16.04.2022 ) https://coord.info/GC9Q3VX
- The users current date was 05. April 2022, 20:30 (GMT+12), where he sees the following:
  - The popup on map shows the event date (incorrectly) as 17.04.2022
  - The cache description itself shows the event date (correctly) as 16.04.2022

**Comment by moving-bits** [comment]
Another user reported getting different event dates on cache popup and cache details screens:

"The two images attached show the same event, they were captured within seconds of each other, just a few minutes before I sent this email.

The event date in the toast popup is incorrect, the date in the full cache description is correct. This problem is causing occasional event confusion.

I assume it is related to to timezones, otherwise it would have been seen and fixed a lot earlier. I am in New Zealand, currently we are UTC +13.

Could the date code in the toast popup please be modified to be identical to that used in the main description please."

|cache popup|cache details|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/d5de4690-8dee-49c7-b1d7-48aa1320ff00)|![image](https://github.com/cgeo/cgeo/assets/3754370/14589d43-779c-4f05-8d46-3cb2c79f4bf4)|
|wrong date|correct date|

system information: (details available upon request)
- c:geo 2023.11.13
- Device type: SM-A217F (a21snnxx, samsung)
- Android version: 12
- Set language: en_NZ (system default)
- System date format: d/MM/yy
- Time zone: GMT+13:00

Ticket 141277

May be related to other time/date issues tickets, eg. #7831, #13515
