### ISSUE TITLE
Geopoint Parse Exception

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5069]
This error started to raise just yesterday on GooglePlay.
Can that be caused by a website change?

Version 2015.06.19
Several Android versions, several devices

Message:
Crashed while loading/opening caches

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: cgeo.geocaching.location.Geopoint$ParseException: 47.42355 11.74533 
at cgeo.geocaching.location.GeopointParser.parse(GeopointParser.java:74)
at cgeo.geocaching.location.Geopoint.<init>(Geopoint.java:57)
at cgeo.geocaching.connector.gc.GCParser.parseCacheFromText(GCParser.java:764)
at cgeo.geocaching.connector.gc.GCParser.parseCache(GCParser.java:371)
at cgeo.geocaching.connector.gc.GCConnector.searchByGeocode(GCConnector.java:179)
at cgeo.geocaching.Geocache.searchByGeocode(Geocache.java:1703)
at cgeo.geocaching.CacheDetailActivity$2.call(CacheDetailActivity.java:340)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
... 4 more
```

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: cgeo.geocaching.location.Geopoint$ParseException: 33.02758 -96.77712 
at cgeo.geocaching.location.GeopointParser.parse(GeopointParser.java:74)
at cgeo.geocaching.location.Geopoint.<init>(Geopoint.java:57)
at cgeo.geocaching.connector.gc.GCParser.parseCacheFromText(GCParser.java:764)
at cgeo.geocaching.connector.gc.GCParser.parseCache(GCParser.java:371)
at cgeo.geocaching.connector.gc.GCConnector.searchByGeocode(GCConnector.java:179)
at cgeo.geocaching.Geocache.searchByGeocode(Geocache.java:1703)
at cgeo.geocaching.CacheDetailActivity$2.call(CacheDetailActivity.java:340)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
... 4 more
```

**Comment by rsudev** [comment]
Meanwhile the reported issues for this ceased again.
I would assume it was a change on the website in conjunction with #5051 - so should be fixed on master.

**Comment by Lineflyer** [comment]
I can still see some occurences on Google Play Console starting with yesterday.
What should be the visual difference on the website for this coordinate parsing failure?
Normally those are always shown as WGS84 on the website...

**Comment by Lineflyer** [comment]
OK, there was a website change last night.
Now this is also appearing to me with 2015.06.07-NB when updating caches.
Refresh caches is hanging in "Creating waypoints".

So this one is an urgent one!

```
08:35:15.773 Debug cgeo 32336  [refresh-1] GET http://www.geocaching.com/seek/cache_details.aspx?decrypt=y&wp=GC4ZEM5&log=y&numlogs=0
08:35:16.875 Debug cgeo 32336  [refresh-1] 200 (1102 ms) GET http://www.geocaching.com/seek/cache_details.aspx?decrypt=y&wp=GC4ZEM5&log=y&numlogs=0
08:35:17.316 Error cgeo 32336  [refresh-1] Geocache.storeCache
08:35:17.316 Error cgeo 32336  cgeo.geocaching.location.Geopoint$ParseException: 51.30675 6.85743
08:35:17.316 Error cgeo 32336  	at cgeo.geocaching.location.GeopointParser.parse(GeopointParser.java:86)
08:35:17.316 Error cgeo 32336  	at cgeo.geocaching.location.Geopoint.<init>(Geopoint.java:57)
08:35:17.316 Error cgeo 32336  	at cgeo.geocaching.connector.gc.GCParser.parseCacheFromText(GCParser.java:764)
08:35:17.316 Error cgeo 32336  	at cgeo.geocaching.connector.gc.GCParser.parseCache(GCParser.java:371)
08:35:17.316 Error cgeo 32336  	at cgeo.geocaching.connector.gc.GCConnector.searchByGeocode(GCConnector.java:179)
08:35:17.316 Error cgeo 32336  	at cgeo.geocaching.Geocache.searchByGeocode(Geocache.java:1703)
08:35:17.316 Error cgeo 32336  	at cgeo.geocaching.Geocache.storeCache(Geocache.java:1611)
08:35:17.316 Error cgeo 32336  	at cgeo.geocaching.Geocache.refreshSynchronous(Geocache.java:1592)
08:35:17.316 Error cgeo 32336  	at cgeo.geocaching.Geocache$4.call(Geocache.java:1585)
08:35:17.316 Error cgeo 32336  	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
08:35:17.316 Error cgeo 32336  	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
08:35:17.316 Error cgeo 32336  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08:35:17.316 Error cgeo 32336  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08:35:17.316 Error cgeo 32336  	at java.lang.Thread.run(Thread.java:818)
```

**Comment by Lineflyer** [comment]
It seems all geocaches with waypoints are affected. Simple traditionals without any waypoint refresh and load OK.

**Comment by rsudev** [comment]
You can see in the waypoint table that the coordinates are now shown in dd.ddd format, no longer in dd° mm.mmm as before...

**Comment by Lineflyer** [comment]
Reopening for test.
@rsudev Will this fix work with both formats? (MinDec and Decimal)

**Comment by Lineflyer** [comment]
Confirmed working (while the website is using decimal format) with 2015.06.08-NB1:
Caches are loaded and refreshed without any exception and resulting waypoints have correct coordinates.
I cannot judge however if it will be still working in case they fall back to MinDec format on the website, but reading the geopointparser unit tests I assume it should work?!
