### ISSUE TITLE
Allow check authentication without need to reenter password

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5601]
##### Actual behavior after performing these steps:

With the new authentication menu the password field is empty when accessing the reauthentication screen. The user has to reenter his password in order to check it.

##### Expected behavior after performing these steps:
The old 'Check Login' function is a procedure well used in my support mail activity and also AFAIR in our FAQ. I would like to see that the old password is kept here, so that we can instruct the user to check the login without the need to enter the password again.

##### Version of c:geo used:
2016.03.29-NB

##### Is the problem reproducible for you?
Yes

**Comment by kumy** [comment]
@Lineflyer I'll do. I admit I have doubt about this specific case. So let's [re-]add it

**Comment by Lineflyer** [comment]
We could also leave it like it is and enforce the user to recheck and reenter his password. But there are some cases where it could be easier for helping users as there are some of them not knowing their password and having it only stored in c:geo which will lead to further clarification needs.

**Comment by Lineflyer** [comment]
Confirmed fixed with 2016.03.31-NB

**Comment by kumy** [comment]
just seen that one button is still present on GK service setting. I have to remove it.

On March 31, 2016 12:37:32 PM GMT+02:00, Lars <notifications@github.com> wrote:
>Assigned #5601 to @kumy.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5601#event-609601980

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
