### ISSUE TITLE
Searching certain TB code freezes app

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5780]
##### Detailed steps causing the problem:
- Debug mode active
- Search for (possibly wrong) tracking code CMPRNP via main screen search field

##### Actual behavior after performing these steps:
Progress windows opens but freezes immediately

##### Expected behavior after performing these steps:
TB opened or correct error message shown

##### Version of c:geo used:
2016.06.10-NB1

##### Is the problem reproducible for you?
Yes

##### System information:
```

##### Other comments and remarks:

**Comment by Bananeweizen** [comment]
Try with the next nightly. I've fixed 2 issues which might be the reason for this. I only saw a freeze when I initially activated debug logging, but never again afterwards.

**Comment by rsudev** [comment]
With debug logging active I still get this effect (no issue when it is deactivated). To me it seems the 'fail on log.e pattern if debug log is activated' is not very useful. Perhaps we should remove it again.

**Comment by Lineflyer** [comment]
I am undecided regarding "abort on log.e":
On one hand it might lead to many complications while testing (where I keep debug mode on), on the other hand (if I understood @samueltardieu correctly) it helps to find hidden problems.

**Comment by SammysHP** [comment]
And this is a hidden problem. ;)

**Comment by Lineflyer** [comment]
@Bananeweizen Confirm, the problem is still there. Is a log needed?

**Comment by rsudev** [comment]
I read again the discussion around the introduction of the 'abort on log.e' feature and the arguments are IMO valid, but we have some edge cases we need to solve to make the feature help and not cause trouble.
In this context we seem to have an unhandled exception in rx, as no connector returned something for this trackable code.
This ends up in our central unhandled exception handler, which in turn calls log.e before proceeding...
Calling Log.e is just natural and correct here, so we might need some way to override the 'abort on log.e' in this case.
Another place is, where the error is handled, logged and then signaled to the user (TrackableActivity,233). Even her doing a Log.e is the natural thing, but an abort is not correct, as the user is made aware of the situation, so no 'hidden' error in this case.

**Comment by Bananeweizen** [comment]
Calling log.e is not correct in the situation, that there are zero results after asking for a trackable. That is a valid result, so it shall not lead to Log.e() at all.

And without our fail on log.e() strategy I surely would not have found the bug that Google Play Services were always used on the master build, even if the device doesn't have Play Services.

**Comment by Bananeweizen** [comment]
@samueltardieu You may want to check my change, since this reverts the #4389 change of you.

@all: I just learned, that the stack trace can be "decoded", e.g. 
```
06-12 15:03:31.497: E/cgeo(1863): Caused by: java.util.NoSuchElementException: Sequence contains no elements
06-12 15:03:31.497: E/cgeo(1863): 	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:116)
```
indicates we are looking for the method ".single()" (because of "OperatorSingle"). That way one can at least find the place relatitvely easily.

**Comment by rsudev** [comment]
I got a freeze now if no network was available, so I demoted the Log.e on no data from server to Log.w as well.
