### ISSUE TITLE
Opencaching UK address change

### ISSUE THREAD

**Issue by deg-pl** [cgeo/cgeo#6083]
Opencaching UK has changed address.
New address of the site: https://opencache.uk
OKAPI address: http://opencache.uk/okapi
Old addresses (opencaching.co.uk, opencaching.org.uk, opencaching.uk) are not longer correct, and are redirecting to GC site.
Now OC UK is based on OC PL current code - the same code like in OC NL and OC RO.
Please adapt c:geo code as soon as posible. Thanks in advance!

Regards!
deg (OC PL and OC UK admin) (sorry for my English ;) )

**Comment by Lineflyer** [comment]
Just out of curiosity:

Why are you doing that?
And why aren't you redirecting the old to the new address?

**Comment by deg-pl** [comment]
We have no contact to Tim Day, who is owner of old domains, and who make the redirection to GC. Old OC UK server was malfunctioning or down from May/June 2016!

With small group of OC enthusiasts from UK (I'm from Poland) we register new domain, take old database from Paul and run new server which now contains all caches and users from "old" OC UK server.

Many times we tried to get in touch with Tim, but without effect...

**Comment by Lineflyer** [comment]
Oh ok. That explains!

**Comment by Lineflyer** [comment]
@Bananeweizen
If you base the change on release we would have the possibility to have it out on the market really soon.

**Comment by Bananeweizen** [comment]
@deg-pl I believe OKAPI is not yet fully functional for OC.UK. When I try to get an OAuth token from within cgeo, then I get this response as JSON:
```
{"error":{"developer_message":"Unrecognized base URL prefix! See `okapi_base_urls` field in the `services\/apisrv\/installation` method. (Recommended base URL to use is 'http:\/\/opencache.uk\/okapi\/'.)","reason_stack":["bad_request"],"status":400,"more_info":"http:\/\/opencache.uk\/okapi\/introduction.html#errors"}}
```
I'm not exactly sure what to make of that, but it surely looks like a server issue. If I may shoot into the blue, I'd say the OKAPI code may internally stumble over your URL not to start with "opencaching", but with "opencache" instead.

**Comment by deg-pl** [comment]
Ok, thanks. Give me a moment ;)

**Comment by deg-pl** [comment]
Could you check again please?
OKAPI had incorrect data stored in cache - now is fixed.
(But it also may be bigger problem (site_url points to http, not https))

**Comment by Bananeweizen** [comment]
@deg-pl Nope. Still the same error (and also the same output when running services/apisrv/installation).

**Comment by Lineflyer** [comment]
Does it make sense to merge the change nontheless (if we are sure the problem is only on server side)?
Pro: It will be in next release coming very soon, Con: We cant test.

**Comment by Bananeweizen** [comment]
@Lineflyer org.uk is broken since months. There is obviously no need to hurry, therefore this should be tested. Please don't wait for this issue, when deciding whether or not to release.

**Comment by deg-pl** [comment]
OK. Problem located and fixed. Could you check it again?

**Comment by Bananeweizen** [comment]
I've checked, and it still doesn't work. This is what I'm testing with, so you should be able to reproduce the error: http://www.opencache.uk/okapi/services/caches/geocache?cache_code=OK007B&fields=code|name|location|type|status|difficulty|terrain|size|size2|date_hidden|trackables_count|owner|founds|notfounds|rating|rating_votes|recommendations|description|hint|images|latest_logs|alt_wpts|attrnames|req_passwd|trackables&attribution_append=none&lpc=all&log_fields=uuid|date|user|type|comment|images&langpref=de|en&consumer_key=93Qu5nwqtBV9UEqaFR7U

**Comment by deg-pl** [comment]
Why do you use "WWW.opencache.uk"? Correct address is just "opencache.uk".

opencache.uk/okapi/services/caches/geocache?cache_code=OK007B&fields=code|name|location|type|status|difficulty|terrain|size|size2|date_hidden|trackables_count|owner|founds|notfounds|rating|rating_votes|recommendations|description|hint|images|latest_logs|alt_wpts|attrnames|req_passwd|trackables&attribution_append=none&lpc=all&log_fields=uuid|date|user|type|comment|images&langpref=de|en&consumer_key=93Qu5nwqtBV9UEqaFR7U works fine!

**Comment by SammysHP** [comment]
Is there a difference? Both should work.

**Comment by deg-pl** [comment]
mail.google.com is not the same as drive.google.com or maps.google.com. OKAPI at OC UK has address http://opencache.uk/okapi and only this address is correct.
OC PL uses opencaching.pl, other sites use www.opencaching.xx - for example. See http://opencache.uk/okapi/services/apisrv/installations

**Comment by SammysHP** [comment]
```
$ host www.opencache.uk
www.opencache.uk has address 89.36.221.105
$ host opencache.uk
opencache.uk has address 89.36.221.105
```

**Comment by deg-pl** [comment]
I don't understand this discussion. ONE AND ONLY OKAPI OC UK address is http://opencache.uk/okapi. Don't use other adresses!

`deg@OCdevel:~$ host ocdevel.best.pl
ocdevel.best.pl has address 77.81.234.157
deg@OCdevel:~$ host centrum.best.pl
centrum.best.pl has address 77.81.234.157
deg@OCdevel:~$ host test.best.pl
test.best.pl has address 77.81.234.157
deg@OCdevel:~$ host manewry.best.pl
manewry.best.pl has address 77.81.234.157
deg@OCdevel:~$ host wiki.best.pl
wiki.best.pl has address 77.81.234.157`

ocdevel.best.pl, centrum.best.pl, test.best.pl, manewry.best.pl, wiki.best.pl (and some more) - all have the same IP addresses, but are completly different services!

**Comment by SammysHP** [comment]
Usually www is an alias and can be used without consequences. www.opencache.uk redirects to opencache.uk. I suggest to use okapi.opencache.uk to avoid confusions.

**Comment by deg-pl** [comment]
Please - change OC UK OKAPI address in c:geo. Nothing else...

**Comment by Bananeweizen** [comment]
@mucek4 Please add the necessary OKAPI key. Be aware the key name has been changed to enforce everyone to use new keys.

> oc_uk2_okapi_consumer_key

**Comment by kumy** [comment]
@Bananeweizen jenkins executors must also be configured with such key, no?

cc @samueltardieu

**Comment by samueltardieu** [comment]
I've added a new key to my slaves.

**Comment by mucek4** [comment]
@Bananeweizen You have changed name, but not key in config file. Is that desired? 
I have changed config - ocuk.okapi.consumer.key and secret to new value.

**Comment by kumy** [comment]
Slaves updated here too.

**Comment by Bananeweizen** [comment]
@kumy, @samueltardieu I wasnt aware your slaves have separate key files, but thanks for catching this. If the next nightly build works fine with oc.UK we can close the issue.

**Comment by Lineflyer** [comment]
Uk Opencaching is back working in newest nightlies. Still see some minor issues here, but closing this one and opening new isse.
