### ISSUE TITLE
Static maps error

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6110]
- enter cache details
- Select Navigate - Save static maps

Maps are loaded but display a yellow error marker and something seems incorrect (did not look in detail)

According to https://developers.google.com/maps/documentation/static-maps/error-messages#warnings this means an error in the request.

**Comment by samueltardieu** [comment]
I can't reproduce it. In the meantime, I've committed 331be7b1b34782218d24d8300da157738891d476 which will log warnings sent back from the API server at warning level.

**Comment by rsudev** [comment]
I checked as well - working for me

**Comment by Lineflyer** [comment]
I can still reproduce with current master.Dont have a debug log right now as I am on the road in Berlin this weekend.
In my installation static maps are disabled, thus only loaded on demand when selecting the mentioned menu item.Maybe this is a difference.


Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: rsudev <notifications@github.com> 
Datum: 11.11.2016  22:42  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu>, Author <author@noreply.github.com> 
Betreff: Re: [cgeo/cgeo] Static maps error (#6110) 

I checked as well - working for me

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rsudev in #6110: I checked as well - working for me"}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/6110#issuecomment-260062300"}}}

**Comment by Lineflyer** [comment]
Had problems to retest this. See #6343

**Comment by Lineflyer** [comment]
Static map loading is working without any "yellow marker" now. Lets close this. 
I will also investigate #6343 once again.
