### ISSUE TITLE
Deprecated gradle function

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6381]
2 deprecated function found in CI build log http://ci.cgeo.org/job/cgeo%20pull%20request/769/console
```
00:13.113  The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
00:13.113  	at org.gradle.api.tasks.compile.JavaCompile.setDependencyCacheDir(JavaCompile.java:245)
00:13.113  	at com.android.build.gradle.tasks.factory.AndroidJavaCompile_Decorated.setDependencyCacheDir(Unknown Source)
00:13.113  	at com.android.build.gradle.tasks.factory.JavaCompileConfigAction.execute(JavaCompileConfigAction.java:131)
00:13.113  	at com.android.build.gradle.tasks.factory.JavaCompileConfigAction.execute(JavaCompileConfigAction.java:39)
00:13.113  	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:142)
00:13.113  	at com.android.build.gradle.internal.TaskContainerAdaptor.create(TaskContainerAdaptor.java:59)
00:13.113  	at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:47)
00:13.113  	at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:89)
00:13.113  	at com.android.build.gradle.internal.TaskManager.createJavacTask(TaskManager.java:1102)
00:13.113  	at com.android.build.gradle.internal.ApplicationTaskManager$13.call(ApplicationTaskManager.java:248)
00:13.113  	at com.android.build.gradle.internal.ApplicationTaskManager$13.call(ApplicationTaskManager.java:241)
00:13.113  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
00:13.113  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
00:13.113  	at com.android.build.gradle.internal.ApplicationTaskManager.createTasksForVariantData(ApplicationTaskManager.java:238)
00:13.113  	at com.android.build.gradle.internal.VariantManager.createTasksForVariantData(VariantManager.java:485)
00:13.113  	at com.android.build.gradle.internal.VariantManager$3.call(VariantManager.java:293)
00:13.113  	at com.android.build.gradle.internal.VariantManager$3.call(VariantManager.java:290)
00:13.113  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
00:13.113  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
00:13.113  	at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.java:44)
00:13.113  	at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:286)
00:13.113  	at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:688)
00:13.113  	at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
00:13.113  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
00:13.113  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
00:13.113  	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:683)
00:13.113  	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
00:13.113  	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
00:13.113  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
00:13.113  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
00:13.113  	at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
00:13.113  	at com.android.build.gradle.BasePlugin$$Lambda$22/709248459.execute(Unknown Source)
00:13.113  	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
00:13.113  	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
00:13.113  	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
00:13.113  	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
00:13.113  	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
00:13.113  	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
00:13.113  	at com.sun.proxy.$Proxy15.afterEvaluate(Unknown Source)
00:13.113  	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
00:13.113  	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
00:13.113  	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
00:13.113  	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
00:13.113  	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
00:13.113  	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
00:13.113  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
00:13.113  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
00:13.113  	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
00:13.113  	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:599)
00:13.113  	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
00:13.113  	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
00:13.113  	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
00:13.113  	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
00:13.113  	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:233)
00:13.113  	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:230)
00:13.113  	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
00:13.113  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
00:13.113  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
00:13.113  	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:160)
00:13.113  	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
00:13.113  	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
00:13.113  	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
00:13.113  	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
00:13.113  	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
00:13.113  	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
00:13.113  	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
00:13.113  	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
00:13.113  	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
00:13.113  	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
00:13.113  	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
00:13.113  	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
00:13.113  	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
00:13.113  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.113  	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
00:13.113  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.113  	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
00:13.113  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.113  	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
00:13.113  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.113  	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
00:13.113  	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
00:13.113  	at org.gradle.util.Swapper.swap(Swapper.java:38)
00:13.113  	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
00:13.113  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.113  	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:50)
00:13.145  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.145  	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
00:13.145  	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
00:13.145  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.145  	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
00:13.145  	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
00:13.145  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.145  	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
00:13.145  	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
00:13.145  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
00:13.145  	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
00:13.145  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
00:13.145  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
00:13.145  	at java.lang.Thread.run(Thread.java:745)
00:13.431  The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
00:13.431  	at org.gradle.api.internal.tasks.DefaultTaskInputs.source(DefaultTaskInputs.java:137)
00:13.431  	at com.android.build.gradle.tasks.factory.AndroidUnitTest$ConfigAction.configureSources(AndroidUnitTest.java:191)
00:13.431  	at com.android.build.gradle.tasks.factory.AndroidUnitTest$ConfigAction.execute(AndroidUnitTest.java:110)
00:13.431  	at com.android.build.gradle.tasks.factory.AndroidUnitTest$ConfigAction.execute(AndroidUnitTest.java:70)
00:13.431  	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:142)
00:13.431  	at com.android.build.gradle.internal.TaskContainerAdaptor.create(TaskContainerAdaptor.java:59)
00:13.431  	at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:47)
00:13.431  	at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:89)
00:13.431  	at com.android.build.gradle.internal.TaskManager.createRunUnitTestTask(TaskManager.java:1586)
00:13.431  	at com.android.build.gradle.internal.TaskManager.createUnitTestVariantTasks(TaskManager.java:1376)
00:13.431  	at com.android.build.gradle.internal.VariantManager.createTasksForVariantData(VariantManager.java:479)
00:13.431  	at com.android.build.gradle.internal.VariantManager$3.call(VariantManager.java:293)
00:13.431  	at com.android.build.gradle.internal.VariantManager$3.call(VariantManager.java:290)
00:13.431  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
00:13.431  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
00:13.431  	at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.java:44)
00:13.431  	at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:286)
00:13.431  	at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:688)
00:13.431  	at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
00:13.431  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
00:13.431  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
00:13.431  	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:683)
00:13.431  	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
00:13.431  	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
00:13.431  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
00:13.431  	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
00:13.431  	at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
00:13.431  	at com.android.build.gradle.BasePlugin$$Lambda$22/709248459.execute(Unknown Source)
00:13.431  	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
00:13.431  	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
00:13.431  	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
00:13.431  	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
00:13.431  	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
00:13.431  	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
00:13.431  	at com.sun.proxy.$Proxy15.afterEvaluate(Unknown Source)
00:13.431  	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
00:13.431  	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
00:13.431  	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
00:13.431  	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
00:13.431  	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
00:13.431  	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
00:13.431  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
00:13.431  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
00:13.431  	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
00:13.431  	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:599)
00:13.431  	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
00:13.431  	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
00:13.431  	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
00:13.431  	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
00:13.431  	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:233)
00:13.431  	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:230)
00:13.431  	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
00:13.431  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
00:13.431  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
00:13.431  	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:160)
00:13.431  	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
00:13.431  	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
00:13.431  	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
00:13.431  	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
00:13.431  	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
00:13.431  	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
00:13.431  	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
00:13.431  	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
00:13.431  	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
00:13.431  	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
00:13.431  	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
00:13.431  	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
00:13.431  	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
00:13.431  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.431  	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
00:13.431  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.431  	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
00:13.431  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.431  	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
00:13.431  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.431  	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
00:13.431  	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
00:13.431  	at org.gradle.util.Swapper.swap(Swapper.java:38)
00:13.431  	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
00:13.431  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.431  	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:50)
00:13.431  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.431  	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
00:13.431  	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
00:13.432  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.432  	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
00:13.432  	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
00:13.432  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
00:13.432  	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
00:13.432  	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
00:13.432  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
00:13.432  	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
00:13.432  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
00:13.432  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
00:13.432  	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Bananeweizen** [comment]
Those are fixed in the Android Gradle Plugin 2.3, which is released today.

**Comment by kumy** [comment]
Is this "Android Gradle Plugin 2.3" related to you PR #6382 ? If yes, message is still present.
http://ci.cgeo.org/job/cgeo%20pull%20request/774/console

**Comment by samueltardieu** [comment]
Confirmed still present.

**Comment by Bananeweizen** [comment]
I dare to disagree. The CI job no longer has that warning, while it was there before. Most recent build as of writing: http://ci.cgeo.org/job/cgeo%20continuous%20integration/1401/console.

**Comment by Lineflyer** [comment]
@kumy Could you recheck this one?

**Comment by Bananeweizen** [comment]
That is no longer there, as I said above. We do meanwhile have some new deprecation warnings, but also those are _not ours_, but instead simply caused by the gradle plugins that we use, including the Android gradle plugin itself. Generally speaking I try to fix every possible issue when upgrading gradle itself or the related Android plugin. And those deprecation warnings are just _warnings_. When upgrading to Gradle 5, the code will no longer be there and our gradle build will just fail. So there is no chance of a "silent failure".
