### ISSUE TITLE
Icons are blurry on non-default display size

### ISSUE THREAD

**Issue by jonnyrobbie** [cgeo/cgeo#6972]
##### Detailed steps causing the problem:
- Set display settings to non default size. (i.e. Phone settings - Display - Display size - Smaller)
- Open C:GEO and show a map with some saved caches (with the floppy icon, log smiley, etc.)

##### Actual behavior after performing these steps:
- The floppy icon/smiley is blurred (rescaled) and the cache type is off the cache bubble center
![screenshot_20180409-165650](https://user-images.githubusercontent.com/1263963/38508425-7d88c544-3c1f-11e8-82e0-3e401d86852c.png)

##### Expected behavior after performing these steps:
- The supplemental icons to be crisp - i.e a vector rendering or not rescaled.
- The cache type icon to be centered.

##### Version of c:geo used:
2018.02.05

##### Is the problem reproducible for you?
**Yes**/~No~

##### System information:
```
--- System information ---
Device: GT-I9195 (lineage_serranoltexx, samsung)
Android version: 7.1.2
Android build: lineage_serranoltexx-userdebug 7.1.2 NJH47F 290ea0ad35
c:geo version: 2018.02.05
Google Play services: enabled - 12.5.21 (040304-189987672)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (manually changed)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (1.5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (1.5 GB free) external non-removable
Geocache data: /storage/BD37-15EF/Android/data/cgeo.geocaching/files/GeocacheData (12.5 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (10.5 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins: none
--- End of system information ---
```

##### Other comments and remarks:
I'm using LineageOS on Samsung Galaxy S4 mini, but I don't think this should be an issue

**Comment by Lineflyer** [comment]
> I'm using LineageOS on Samsung Galaxy S4 mini, but I don't think this should be an issue

Well, lets say: I have this device here, but it has no such option to alter the display size as you mentioned under the default OS.

**Comment by jonnyrobbie** [comment]
Well, LOS14 is equivalent to Android 7. Maybe the ability to scale ui was added somewhere between that. What about phones with stock os where there introduced this ability?

**Comment by Lineflyer** [comment]
Mmh.. I need to check.
What is the display resolution used in your constellation/setting?

**Comment by jonnyrobbie** [comment]
It's not really a resolution change on a display server level (SurfaceFlinger or whatever andriod uses). It's a UI scale thing. Here's a video of it in action: https://a.pomf.cat/yxqimk.mp4 (I hope it works...)

**Comment by Lineflyer** [comment]
Thanks, the video made it quite clear.
I have a similar feature on my Samsung S7. Will give it a try if time permits.

I am not the right person to judge, whether we can rectify this, however I consider it a very rare issue. 
At least I haven't seen this kind of glitches on the mal on all native resolutions I tested on different devices.

**Comment by rsudev** [comment]
Some comments from me:
We currently don't have SVGs for most of the items the markers are composed of, so 'not scaling' is not a real option right now.
The misplacement of the cache type is likely due to the fact, that we tailor it to the slightly different marker 'forms' in the various resolutions we support, and the non-standard on you choose seemingly falls back to something not working.

**Comment by jonnyrobbie** [comment]
> so 'not scaling' is not a real option right now.

While vector graphic icons would solve the issue, what I meant was something different. Look at this comparison I made
![cgeo_scale](https://user-images.githubusercontent.com/1263963/39992622-acb1ddbe-5773-11e8-8043-880c777606d3.jpg). You can see that the underlay stays the same scale, but those icons are scaled down - that's where the blur gets introduced. I don't know the exact icon scaling mechanics of the framework you use, but woulnd't it be possible to make sure that the icon stays the same resolution (so in a way somewhat ignoring and overriding that system scale) no matter the android UI scale?

**Comment by jonnyrobbie** [comment]
I have not set up a build environment yet, but I was trying to look through android dev documentation and I found what could be possible a solution. I'm not sure if you've been able to reproduce the issue, but https://developer.android.com/training/multiscreen/screendensities page, section "Provide alternative bitmaps", the Tip:

> Tip: If you have some drawable resources that the system should never scale (perhaps because you perform some adjustments to the image yourself at runtime), you should place them in a directory with the nodpi configuration qualifier. Resources with this qualifier are considered density-agnostic and the system will not scale them.

Maybe that would solve the issue quite simply.

**Comment by rsudev** [comment]
Not sure if this will solve the issue. We have these markers available in a number of resolutions as they are otherwise far too small or overly large on the ends of the supported dpi spectrum.
As I didn't yet look into how this ends up in the code handling the marker composition  I currently cannot say whether it is solvable and how easy that might be.
In case you want to take a look, it is in the createWaypointMarker() method in cgeo.geocaching.utils.MapUtils.java.

**Comment by moving-bits** [comment]
@jonnyrobbie
Can you re-check on your device? We did some icon fixes for #5193 and #7793 - maybe the problem you have described in this issue is fixed by that as well, as we changed the mechanism overlay icons are displayed and scaled.

**Comment by jonnyrobbie** [comment]
Version 2019.09.08 of c:geo, the issue still persists. When I got a notification of this thread, I honestly got a bit uncertain if I still have this issue and I had to double-check, but it looks like I've just tuned out the issue. It's definitely still there. Still the same LOS build as before.

**Comment by moving-bits** [comment]
Sad to hear. But thanks for your feedback!

I cannot reproduce this issue here yet. Using an emulated Nexus 5X running on Android 8.1 I do have the menu option to set display size to "smaller", but the icons don't get blurry:

![image](https://user-images.githubusercontent.com/3754370/65837696-d41ecb00-e2fa-11e9-9c81-3e718f127c3a.png)

(Comparing Google Maps and OSM, each having screen size "default" on top, and "smaller" below.)

Maybe it's an edge case depending on the specific resolution and dpi changes involved. Do you happen to have a different device for testing to cross check if it happens there as well? (eg different vendor, different screen resolution)

**Comment by jonnyrobbie** [comment]
Hey, I don't know, how long has it been there, but checking "Settings - Map - Scale Map Text" fixed the icon issue. This however makes the map text rendering smaller, but it fixes the icon scaling. Now if there was an option so set those two indepedently.

**Comment by fm-sys** [comment]
This will (hopefully) get obsolete with #11454. I hope it's ok for everyone if I close this issue in preparation, as we otherwise will forget this old issue again...

Also see https://ztnfny.github.io/cgeoicons/index.html

**Comment by jonnyrobbie** [comment]
As I no longer have an access to the device, I'm not personally affected by this bug anymore and cannot comment on its status.
