### ISSUE TITLE
Android title bar color is inconsistent

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7246]
##### Detailed steps causing the problem:
- Open c:geo
- Check title bar color - black, seems ok
- Open Settings
- Check title bar color - light blue - looks odd.

![2019-01-22 23 13 56](https://user-images.githubusercontent.com/918446/51569003-6f71bd80-1e9b-11e9-8dbd-ac9f91754cad.jpg)
![2019-01-22 23 13 49](https://user-images.githubusercontent.com/918446/51569004-6f71bd80-1e9b-11e9-970f-26a4b0af4d49.jpg)

##### Version of c:geo used:
master + su

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: SM-A320FL (a3y17ltexc, samsung)
Android version: 8.0.0
Android build: R16NW.A320FLXXU3CRH2
c:geo version: 2019.01.22-2b09508 developer build
Google Play services: enabled - 14.7.99 (040306-223214910)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_AU
System date format: d/M/yy
Debug mode active: yes
System internal c:geo dir: /data/user/0/cgeo.geocaching (1.1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (1.0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1.0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (360.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   Geocaching.su: Logged in (Login OK)
Installed c:geo plugins:  none
--- End of system information ---
```
##### Other
Appeared after targetSDK change, maybe you want separated label for it...

**Comment by Lineflyer** [comment]
Thanks @okainov 

> Appeared after targetSDK change, maybe you want separated label for it...

For now I stick with "regression", however @rsudev might descide to create one of better overview. Or we can use a project for that.

**Comment by Lineflyer** [comment]
> For now I stick with "regression", however @rsudev might descide to create one of better overview. Or we can use a project for that.

Rethinking this, I created "sdk26-Regression"

**Comment by Lineflyer** [comment]
In fact I was not aware until now, that the running app changes the device title bar color. Interesting.
I meanwhile opend some other dedicated issues about style issues after targetsdk change.

In general IMHO the settings screen design is much more consistent in itself than other designs outside the settings tree. 
If someone can explain the technical difference we might be able to judge which way to go to make it consistent in one or the other way.

**Comment by moving-bits** [comment]
We also have inconsistent coloring on the main screen's titlebar:

![image](https://user-images.githubusercontent.com/3754370/51713495-6404ca80-2032-11e9-9b80-ffe6c4fe4abe.png)

(see background of title and its padding, which is slightly darker)

**Comment by Lineflyer** [comment]
@moving-bits This should be tackled meanwhile?

**Comment by fm-sys** [comment]
Should be implicitly fixed with #8741

**Comment by moving-bits** [comment]
At least on currently released version it's still not consistent - title bar itself stays black (ok), but the orange divider is visible on mainscreen only. And the device title bar also changes its color (for me: from "black" on mainscreen to "blue" in settings).

But let's not dive into this for now, as it's that way since a long time (at least partly). We should keep this in mind as part of #9373.
