### ISSUE TITLE
waypoints not shown

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7526]
I've a cache with a couple of waypoints, which are up to 5 km away from the cache. When I chose to display this cache, all waypoints (and the cache marker itself) are shown. This changes when I pan around or zoom in, so that the cache to which those waypoints belong to, is no longer visible. (But not directly, so maybe there is some sort of "buffer zone" in which the cache is still counted as visible?)

##### Expected behavior after performing these steps:
If a waypoint falls into the visible viewport it should be shown, even if the cache it belongs to is no longer part of the visible viewport. (But still respecting the other filters like "too many waypoints", cache type filter etc.)

##### Version of c:geo used:
Current master, but this happens since a long time.

##### Is the problem reproducible for you?
Yes

**Comment by rsudev** [comment]
I guess this is an issue we have already listed (and is on my radar, sort of). Would be good to know which map source you refer to (google, mf v3, new mf).

**Comment by moving-bits** [comment]
I couldn't find an issue for this, just for the opposite case (waypoints leaking from other lists), so I opened a new one. Feel free to link & close, if there is already an issue for this.

This seems to be happening for Mapsforge new map only. (This is the map type I'm using nearly exclusively, but a quick test with Google Maps and old Mapsforge did not show this problem.)

**Comment by Lineflyer** [comment]
I also remember this somehow but thought it was closed already.
@moving-bits Can you please give the GC-code of the mentioned cache?

**Comment by moving-bits** [comment]
> @moving-bits Can you please give the GC-code of the mentioned cache?

Alas, no in this case, as I had created my own GPX file with a single cache with a non-existing GC-Code, just to create "my own" cache in c:geo, and then had added waypoints for every final of my own caches using the waypoint feature in c:geo.

(The reason for doing it this way was that I wanted to see my own finals in the map [useful when doing maintenance], without having to disactivate "hide own or found caches". If I could activate / disactivate it separately... but that's a separate issue.)

**Comment by Lineflyer** [comment]
Probably related to #5900 or linked issues but should be solved.

**Comment by moving-bits** [comment]
> Probably related to #5900 or linked issues but should be solved.

could be related to the original issue mentioned in #5900, but that one later on lead to the "waypoints of caches in two different lists" (which is a separate issue of "too much waypoints shown")

**Comment by rsudev** [comment]
This should be solved with #7657. Can you please cross-check?

**Comment by moving-bits** [comment]
> This should be solved with #7657. Can you please cross-check?

Did a quick test with the emulator first, and a real device then, comparing current release version to current master: From this test it looks good - I can zoom down to 10m, and still see waypoints of my "faraway" cache (whereas before waypoints got lost at 50m zoom at the latest). 👍

**Comment by jakedot** [comment]
> Did a quick test with the emulator first, and a real device then,
comparing current release version to current master

Great news! Keep up the good work! :)

**Comment by rsudev** [comment]
Thanks for cross-checking, closing for now.
