### ISSUE TITLE
Missing hint button after bulk offline download

### ISSUE THREAD

**Issue by chstdu** [cgeo/cgeo#8107]
**Bug description**
After downloading several geocaches via the bulk offline storing method, the hint button at the geocache overview is (still) missing although the hint was already downloaded.

**To Reproduce:**
1. Go to 'Live Map'
2. Click on 'Store all' ('Alle speichern' in German)
3. Click on one of the stored geocaches

**Actual behavior/state after performing these steps:**
There is no hint button.

**Expected behavior/state after performing these steps:**
There should be a hint button.

**Additional context:**
If you click on the update button (the two circular arrows), an online update is performed and the hint button is finally displayed.

**Version of c:geo used:**
2020.01.16-RC

**Is the problem reproducible:**
Yes (very often)

**Screenshots:**
[Screenshot with hint button](https://ibb.co/PN2qn9S)

**System information:**
```
--- System information ---
Device: Pixel 3a (sargo, google)
Android version: 10
Android build: QQ1A.200105.002
c:geo version: 2020.01.16-RC
Google Play services: enabled - 20.1.04 (120400-288960190)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (34,4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (34,4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (34,4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (616,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / BASIC
   opencaching.de: Logged in (Anmeldung OK)
Geocaching.com date format: dd.MMM.yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by moving-bits** [comment]
@chstdu: Is this with "live mode" enabled? Then this may be #7634.

**Comment by chstdu** [comment]
@moving-bits Thank you for your quick answer. Yes, you are right. "Live mode" is enabled. When I tried it with "live mode" disabled a few times right now, the button finally showed up for a new cache (even after bulk download) but still did not show up after bulk download for a cache which I already found. So I guess it is at least very similar to #7634.

**Comment by Lineflyer** [comment]
@chstdu It should be solved in current release 2020.10.10. Please kindly report if you keep having this problem.

**Comment by deltamelter** [comment]
This is still an issue in recent nightly... spent the whole trip trying to disable toggle talking button, thinking it was pushing the hint button off the screen.  Then found this and resfreshing the cache lets the hint button appear
