### ISSUE TITLE
[Nightly] Offline Log gets not saved

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8973]
**Describe the bug:**
The offline log entry gets not saved, if it only contains the automatically inserted signature.

**To Reproduce:**
my workflow while I'm on the road is usually:
1.  Click on 'Log Visit'
2. (The signature gets inserted automatically)
3. directly press back button to leave logging activity without writing some additional text

**Actual behavior/state after performing these steps:**
there is no offline log created

**Expected behavior/state after performing these steps:**
offline log including the signature should be stored, so that the offline counter for the next logs is correct and the cache easily be found for finishing the log text later. 

It worked before so it probably came with the log activity change... @eddiemuc could you please look at this?

**Version of c:geo used:**
NB 2020.09.07

**Comment by eddiemuc** [comment]
Should be fixed with PR #8967 , can you retry with newest nightly?

**Comment by eddiemuc** [comment]
Just read your description more throughly. Actually, I thought that this is the wanted behaviour (if you just enter log dialog but leave it immediately via back button then no save should occur). Only if you explicitely save this state via "save offline" it should be saved (the later did not occur any more, this is correctd with above mentioned PR).

Is it really wanted that an offline log is saved when log dialog is immediately left with "back" button? This is usually a sign that the dialog was entered by accident.

**Comment by fm-sys** [comment]
Retested it with `2020.09.08-NB`, unfortunately the bug still exists

**Comment by rsudev** [comment]
IIRC earlier (like last year?) the behaviour was to discard the log if no message was entered. So if you had an automatic log message, you would have to clear the log and then leave to discard it.
@fm-sys As a side note: perhaps using the 'log offline' setting fits your use case better in any case. If this is activated, a pop-up menu is shown where you can select the log type. The message template gets inserted and the dialog is not shown at all. But there is also an entry to select 'online-log' on a case by case basis

**Comment by fm-sys** [comment]
> Is it really wanted that an offline log is saved when log dialog is immediately left with "back" button? This is usually a sign that the dialog was entered by accident.

If someone doesn't want that the offline log is saved, he will have to clear the log text before leaving the activity. That's how it was done at the old logging page too. And pressing the back button is easier than using the "save offline" with only one free hand ;-)

@rsudev thanks for the hint! I will look into this...

**Comment by eddiemuc** [comment]
I can restore back this behaviour although it seems very strange to me, because it means.
* If you have an active signature, pressing "back" will save a log
* If you don't have an active signature, pressing "back" will NOT save.

(in case you wonder why I changed this stuff in the first place: turns out that up to before my change the log was saved up to three times before, depending on your usage scenario)

**Comment by eddiemuc** [comment]
I checked further in current release, and it gets more strange (to me):
nowadays, when you have an already saved offline log, when you open it and delete all the text, then leave the dialog via back button, then this change does NOT get saved (the offline log is still there, and when you return to offline log, the just-deleted-text is there again. When you e.g. additionally changed the log type, this is reverted as well).

Is it ok when this behaviour does not occur any more (and that in this case the log is saved with an empty text)?

And what should happen when I open log offline dialog with no active signature and press "back" immediately? Should there be a log save or not (today there is no save in this case)?

**Comment by SammysHP** [comment]
> nowadays, when you have an already saved offline log, when you open it and delete all the text, then leave the dialog via back button, then this change does NOT get saved (the offline log is still there, and when you return to offline log, the just-deleted-text is there again. When you e.g. additionally changed the log type, this is reverted as well).

I think this is by design to prevent accidental deletion of the log.

> And what should happen when I open log offline dialog with no active signature and press "back" immediately? Should there be a log save or not (today there is no save in this case)?

IIRC we decided to not save a log in this case, only when explicitly saved via the menu.

**Comment by eddiemuc** [comment]
I added this special handling in PR #8975 
* c:geo will now save also  when signature is active and back button is immediately pressed after entering offline log dialog. It will not save if signature is not active and back button is pressed immediately
* c:geo will NOT save if in already saved log the text was fully deleted. It will save when any other fields was (additionally) modified
