### ISSUE TITLE
Next beta/feature release (last one before SAF?)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9807]
Would you agree with the plan to:
1. Wait some more days to see if there are any urgent problems with current release 2021.01.16
2.  Cut off a new feature release from `master` into `release` (seeing that we have >140 new commits on `master` its already quite a bunch of changes)
3. Publish a new beta and finally release from there if OK

After branching in step 2 we could merge SAF.
That will allow most testing and bugfixing time on `master` for SAF and maybe an overnext release which contains mainly the SAF changes.

**Comment by moving-bits** [comment]
Yes, sounds reasonable. It will be good to get SAF changes into master soon, so that keeping two branches aligned for this huge change will come to an end.

**Comment by eddiemuc** [comment]
Makes a lot of sense. Thank you!

**Comment by moving-bits** [comment]
What needs to be done / fixed / included before we can branch current `master` and prepare a new beta version?
Feel free to add or comment here.

I'd like to include #9836, #9839 (already prepared) and a fix for #4351 before branching.

@Lineflyer: Can you give me some feedback whether https://github.com/cgeo/cgeo/issues/4351#issuecomment-764869144 is what you'd like to see as archived marker background color?

Anything else that should be included for next beta?

**Comment by Lineflyer** [comment]
AFAICS all PR / isues mentioned by @moving-bits are merged/fixed by now.

Also from my side it looks rather complete and master looks stable (as far as I can judge).

On support mail there are two issues reported by users:

#9833  -> no idea if this is a real bug/regression or something else. It seems not to affect all users at least. Anyway we can still fix it later.
#9844 -> Looks like a regression from introducing the DNF feature and should be fixed for next release

**Comment by Lineflyer** [comment]
Three options:
- Fix #9844 (on master) and branch + release beta afterwards
- Branch now, fix #9844 (on release) and release beta afterwards
- Branch and release beta now, fix #9844 afterwards and release again

As we are not in a hurry, I propose the first option or (if we want to continue with new features on master urgently) the second option.

**Comment by fm-sys** [comment]
#9848 provides a fix for #9844, so we can merge it to master and start a new beta afterwards...

**Comment by Lineflyer** [comment]
Thanks @fm-sys , just merged and triggered a new nightly to give it a quick test

@bekuno 
I guess we should merge #9838 after branching to allow more time for testing if there are any unwanted effects?

**Comment by bekuno** [comment]
> I guess we should merge #9838 after branching to allow more time for testing if there are any unwanted effects?

I do not expect side effects. But it is on the other side not necessary for the next release. It can wait.

**Comment by bekuno** [comment]
The problem described in #9850 would be a blocker for the release, imho.

@Lineflyer Please test if I had a error in my workflow or if we have a another way to restore a backup from another mobile.

**Comment by fm-sys** [comment]
> The problem described in #9850 would be a blocker for the release, imho.
> 


IMHO we can fix this at `release` branch if it's really necessary to fix it. But as described by @Lineflyer in https://github.com/cgeo/cgeo/issues/9850#issuecomment-766331844 this will only happen at the very first app start directly after permission granting...

**Comment by Lineflyer** [comment]
> The problem described in #9850 would be a blocker for the release, imho.
> @Lineflyer Please test if I had a error in my workflow or if we have a another way to restore a backup from another mobile.

As just replied over in that issue, I think it is a older issue (which is limited to first start).
Not a regression, therefore it shouldn't block the beta I guess.

**Comment by moving-bits** [comment]
#9850 is actually introduced by the installation wizard, at least partly.
I've prepared a workaround for it, see #9853. Should be included in the upcoming release.

**Comment by Lineflyer** [comment]
@moving-bits 
Do you think the wizard is working fine now with your workaround?
I guess anyway beta testers will most likely not stumble upon it as these are usually existing users only (upgrading from a previous version).

So "Go" for branching and beta?

**Comment by moving-bits** [comment]
Yes from my side.

I've been able to reproduce the situation described in #9850, and with my workaround (resetting external storage path on storage permission request) everything worked as expected.

**Comment by Lineflyer** [comment]
OK, I will prepare merging branches and publishing a beta.

**Comment by Lineflyer** [comment]
- Branch `release` has been fast-forwarded to head of `master`
- Changelogs modified and initialized on `master`
- Beta version smoke tested (Android 11 and Android 10)
- Beta version uploaded on Google Play for our beta users (might take some hours until available)

Thanks @cgeo/team

**Comment by Lineflyer** [comment]
Beta version 2021.01.24-RC is live for our beta testers now.

**Comment by moving-bits** [comment]
Thanks @Lineflyer for preparing the beta version (and thanks @cgeo/team for preparing all the good stuff in it :-))

Looking forward to current master and a more in-depth dive into SAF!

**Comment by Lineflyer** [comment]
I tried to summarize the "ToDo" before releasing the current beta here:
https://github.com/cgeo/cgeo/projects/18

**Comment by Lineflyer** [comment]
Seeing that we should fix the website regression we should think about whether we can release the RC.
Based on the issues collected above there are only minor thinks to solve....someone on it or shall we release despite these regressions?

**Comment by moving-bits** [comment]
I've finalized & merged the fix for #9999 on `release`; not working currently on the other issues in https://github.com/cgeo/cgeo/projects/18; Play Console seems to be fine for the RC - so "go" for a release from my side.

**Comment by moving-bits** [comment]
Hm, something was nagging at me the last hours, something missing in the list. Finally found it: What about #9875? Somehow this got lost from the project list. I guess this is still happening?

Do we have an idea when it did occur the first time in the nightlies? This would help to reduce the area of commits which may be triggering that behavior.

**Comment by Lineflyer** [comment]
As discussed in our virtual team meeting today, Iwe are going to release based on the current state of `release` rather soon.
We do still have some minor regression (see  https://github.com/cgeo/cgeo/projects/18), however as we had the - already fixed - website change we will release now.

But we forgot to fix #9999 (the changed profile links) also for the `legacy` branch/version. Do we want to do this / can someone do this?

As things are easier when releasing both versions combined, we should wait for this (or decide to not fix it).

**Comment by Lineflyer** [comment]
Thanks @moving-bits for reminding me of #9285 which concludes, that we are unable to push an update for the legacy version (as we target a to low SDK). 
So lets stay with that regression for the legacy users..luckily only minor functions are affected.

I will therefore go for release of the beta version now:


- [ ] Check/Insert correct version name as headline in ```changelog-release.xml``` 
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
We are done, release 2021.02.14 is live.
Thanks to all contributors for your great work!!!
